#pragma once

#include <limits.h>
#include <stdbool.h>

typedef enum {
    BACKEND_C,
    BACKEND_LLVM,
} Backend;

typedef enum {
    TARGET_ISIZE_64,
    TARGET_ISIZE_32,
} Target;

typedef enum {
    // Parsing
    ERROR_INVALID_TOKEN,
    ERROR_EXPECTED_TOKEN,
    ERROR_EXPECTED_EXPRESSION,
    ERROR_EXPECTED_DEFINITION,
    ERROR_INVALID_TOKEN_AFTER_EXTERN,
    ERROR_EMPTY_CHAR,
    ERROR_MULTIPLE_CHAR,
    ERROR_ESCAPE_SEQUENCE,
    ERROR_UNTERMINATED_STRING,

    // Role analysis
    ERROR_RECURSIVE_DEPENDENCY,
    ERROR_EXPECTED_VALUE,
    ERROR_EXPECTED_TYPE,
    ERROR_MULTIPLE_DEFINITION,
    ERROR_MULTIPLE_EXTERN_DEFINITION,
    ERROR_UNDEFINED_MODULE,
    ERROR_UNDEFINED_NAME,
    ERROR_UNDEFINED_NAME_FROM_MODULE,
    ERROR_DEREF_OPERAND_ROLE,
    ERROR_ACCESS_OPERAND_ROLE,
    ERROR_CALL_OPERAND_ROLE,
    ERROR_INDEX_OPERAND_ROLE,

    // Type analysis
    ERROR_ENUM_EXPECTS_INT_TYPE,
    ERROR_ARRAY_TYPE_EXPECTS_LENGTH_TYPE,
    ERROR_UNARY_UNEXPECTED_OPERAND,
    ERROR_BINARY_UNEXPECTED_OPERANDS,
    ERROR_DEREF_UNEXPECTED_OPERAND,
    ERROR_CAST,
    ERROR_SLICE_CTOR_EXPECTS_POINTER,
    ERROR_TYPE_CONSTRUCTOR_TYPE,
    ERROR_CALLEE,
    ERROR_ARGUMENT_COUNT,
    ERROR_FIELD_COUNT,
    ERROR_LINEAR_CTOR_COUNT,
    ERROR_INDEX_COUNT,
    ERROR_INDEX_OPERAND,
    ERROR_UNDEFINED_TYPE_SCOPE,
    ERROR_UNDEFINED_TYPE_FIELD,
    ERROR_EXPECTED_VALUE_TYPE,
    ERROR_EXPECTED_MUTABLE_PLACE,
    ERROR_CONST_INIT,
    ERROR_CONST_INT_OVERFLOW,
    ERROR_CONST_NEGATIVE_SHIFT,
    ERROR_TYPE_INFERENCE,
    ERROR_EMPTY_ARRAY,
    ERROR_EMPTY_STRUCT,
    ERROR_SWITCH_INCOMPATIBLE_CASES,
    ERROR_MISPLACED_BREAK,
    ERROR_MISPLACED_CONTINUE,
    ERROR_RETURN_MISSING_VALUE,
    ERROR_RETURN_EXPECTED_VALUE,
    ERROR_MISSING_RETURN,
    ERROR_MAIN_SIGNATURE,
    ERROR_TYPE_ARGUMENT_INFERENCE,
    ERROR_TYPE_UNKNOWN_TYPE_SIZE,
    ERROR_TYPE_UNKNOWN_TYPE_ALIGNMENT,
    ERROR_INDEX_UNKNOWN_TYPE_SIZE,
    ERROR_TAGGED_TYPE_WRONG_COUNT,
    ERROR_WRONG_COUNT,
    ERROR_DUPLICATE_SWITCH_CASE,
    ERROR_ELSE_CASE_UNREACHABLE,
    ERROR_SWITCH_NOT_EXHAUSTIVE,

    // Linear analysis
    ERROR_LINEAR_ASSIGNMENT,
    ERROR_CONSUMED_VALUE_USED,
    ERROR_CONSUMED_IN_LOOP,
    ERROR_MOVE_BORROWED,
    ERROR_BORROWED_MUTABLE_SHARED,
    ERROR_MULTIBLE_MUTABLE_BORROWS,

    ERROR_END,

    // Notes
    NOTE_REPLACE_LET_WITH_MUT,
    NOTE_PREVIOUS_DEFINITION,
    NOTE_PREVIOUS_BUILTIN_DEFINITION,
    NOTE_PRIVATE_DEFINITION,
    NOTE_FORGOT_IMPORT,
    NOTE_RECURSION,

    NOTE_END,
} ErrorKind;

typedef enum {
    #define KEYWORD(keyword) TOK_KW_##keyword,
    #include "keyword-defs"

    #define TOKEN(token, s) TOK_##token,
    #include "token-defs"
} TokenTag;

typedef enum {
    SYM_UNDEFINED,
    SYM_BUILTIN,
    SYM_GLOBAL,
    SYM_LOCAL,
} SymbolKind;

typedef enum {
    TYPE_INVALID,

    BUILTIN_TYPE_START = INT_MIN,
    TYPE_VOID = BUILTIN_TYPE_START,
    #define TYPE(type) TYPE_##type,
    #include "simple-types"
    BUILTIN_TYPE_END,

    BUILTIN_MACRO_START = BUILTIN_TYPE_END,
    BUILTIN_ALIGNOF = BUILTIN_MACRO_START,
    BUILTIN_SIZEOF,
    BUILTIN_CAST,
    BUILTIN_ZERO_EXTEND,
    BUILTIN_SLICE,
    BUILTIN_AFFINE,
    BUILTIN_ARRAY_LENGTH_TYPE,
    BUILTIN_MACRO_END,

    BUILTIN_TERM_END = BUILTIN_MACRO_END,

    TERM_COUNT = 1,
    BUILTIN_SIZE = TERM_COUNT,
    BUILTIN_ALIGNMENT,
    TERM_GLOBAL_COUNT,
} PrimitiveTerm;

typedef enum {
    TIR_ERROR,

    TIR_TYPE_START,
    TIR_PRIMITIVE_TYPE = TIR_TYPE_START,
    TIR_ARRAY_TYPE,
    TIR_ARRAY_LENGTH_TYPE,
    TIR_PTR_TYPE,
    TIR_MUT_PTR_TYPE,
    TIR_SLICE_TYPE,
    TIR_MUT_SLICE_TYPE,
    TIR_FUNCTION_TYPE,
    TIR_TAGGED_TYPE,
    TIR_STRUCT_TYPE,
    TIR_ENUM_TYPE,
    TIR_LINEAR_TYPE,
    TIR_TYPE_PARAMETER,
    TIR_TYPE_END,

    // index is unused
    TIR_VALUE_START = TIR_TYPE_END,
    TIR_FUNCTION = TIR_VALUE_START,

    // index points to the name of the function
    TIR_EXTERN_FUNCTION,

    // index points to the name of the var
    TIR_EXTERN_VAR,

    // index points to the 64-bit value in extra
    TIR_CONST_INT,

    // index points to the 64-bit value in extra
    TIR_CONST_FLOAT,

    // index is unused
    TIR_CONST_NULL,

    // index points to the string
    TIR_STRING,

    // index is the variable index
    TIR_VARIABLE,
    TIR_MUTABLE_VARIABLE,

    TIR_LET,
    TIR_MUT,

    TIR_PLUS,
    TIR_MINUS,
    TIR_NOT,
    TIR_DEREF,
    TIR_ADDRESS,
    TIR_ADDRESS_OF_TEMPORARY,

    TIR_ADD,
    TIR_SUB,
    TIR_MUL,
    TIR_DIV,
    TIR_MOD,

    TIR_AND,
    TIR_OR,
    TIR_XOR,
    TIR_SHL,
    TIR_SHR,

    TIR_EQ,
    TIR_NE,
    TIR_LT,
    TIR_GT,
    TIR_LE,
    TIR_GE,

    TIR_ASSIGN,
    TIR_ASSIGN_ADD,
    TIR_ASSIGN_SUB,
    TIR_ASSIGN_MUL,
    TIR_ASSIGN_DIV,
    TIR_ASSIGN_MOD,
    TIR_ASSIGN_AND,
    TIR_ASSIGN_OR,
    TIR_ASSIGN_XOR,

    TIR_ITOF,
    TIR_ITRUNC,
    TIR_SEXT,
    TIR_ZEXT,
    TIR_FTOI,
    TIR_FTRUNC,
    TIR_FEXT,
    TIR_PTR_CAST,
    TIR_NOP,
    TIR_ARRAY_TO_SLICE,

    TIR_CALL,
    TIR_INDEX,
    TIR_SLICE,
    TIR_ACCESS,
    TIR_NEW_STRUCT,
    TIR_NEW_ARRAY,

    TIR_IF,
    TIR_SWITCH,
    TIR_LOOP,
    TIR_BREAK,
    TIR_CONTINUE,
    TIR_RETURN,

    TIR_VALUE_END,

    TIR_MACRO = TIR_VALUE_END,
    TIR_MODULE,

    // a is the inner term
    // b points to the number of type parameters followed by the types
    TIR_GENERIC,
} TirTag;

static inline bool is_tir_type(TirTag tag) {
    return tag >= TIR_TYPE_START && tag < TIR_TYPE_END;
}

static inline bool is_tir_value(TirTag tag) {
    return tag >= TIR_VALUE_START && tag < TIR_VALUE_END;
}

typedef enum {
    VALUE_INVALID,
    VALUE_TEMPORARY,
    VALUE_PLACE,
    VALUE_MUTABLE_PLACE,
    VALUE_MULTIVALUE,
} ValueCategory;

typedef enum {
    // Statement

    MIR_PARAM,
    MIR_ALLOC,
    MIR_ASSIGN,

    // Value

    MIR_INT,
    MIR_FLOAT,
    MIR_STRING,
    MIR_NULL,
    MIR_TIR_VALUE,

    // Pointer operator

    MIR_ADDRESS,
    MIR_DEREF,

    // Arithmetic operator

    MIR_MINUS,
    MIR_ADD,
    MIR_SUB,
    MIR_MUL,
    MIR_DIV,
    MIR_MOD,

    // Bitwise operator

    MIR_NOT,
    MIR_AND,
    MIR_OR,
    MIR_XOR,
    MIR_SHL,
    MIR_SHR,

    // Comparator

    MIR_EQ,
    MIR_NE,
    MIR_LT,
    MIR_GT,
    MIR_LE,
    MIR_GE,

    // Cast

    MIR_ITOF,
    MIR_ITRUNC,
    MIR_SEXT,
    MIR_ZEXT,
    MIR_FTOI,
    MIR_FTRUNC,
    MIR_FEXT,
    MIR_PTR_CAST,
    MIR_NEW_SLICE,

    // Access

    MIR_INDEX,
    MIR_CONST_INDEX,
    MIR_SLICE_INDEX,
    MIR_ACCESS,

    // Control flow

    MIR_CALL,
    MIR_BR,
    MIR_BR_IF,
    MIR_BR_IF_NOT,
    MIR_RET_VOID,
    MIR_RET,
} MirTag;
